# Project: main
# Makefile created by Dev-C++ 5.2.0.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = LinkList.o main.o $(RES)
LINKOBJ  = LinkList.o main.o $(RES)
LIBS     = -L"F:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc  
INCS     = -I"F:/Program Files (x86)/Dev-Cpp/MinGW32/include" 
CXXINCS  = -I"F:/Program Files (x86)/Dev-Cpp/MinGW32/include" 
BIN      = main.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS   = $(INCS)  
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before main.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "main.exe" $(LIBS)

LinkList.o: LinkList.c
	$(CC) -c LinkList.c -o LinkList.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
